service: cloudx-import-service

frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  httpApi:
    cors: true
    authorizers:
      basicAuthorizer:
        type: request
        functionArn: arn:aws:lambda:us-east-1:261414472581:function:cloudx-authorization-service-dev-basicAuthorizer
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 's3:ListBucket'
          Resource: 'arn:aws:s3:::${self:custom.BUCKET_NAME}'
        - Effect: Allow
          Action: 's3:*'
          Resource: 'arn:aws:s3:::${self:custom.BUCKET_NAME}/*'
        - Effect: Allow
          Action: 'sqs:*'
          Resource: 'arn:aws:sqs:us-east-1:261414472581:cloudx-products-service-dev-catalogItemsQueue'
  environment:
    SQS_URL: 'https://sqs.us-east-1.amazonaws.com/261414472581/cloudx-products-service-dev-catalogItemsQueue'

custom:
  BUCKET_NAME: 'ng-store-file-import'

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - httpApi:
          method: get
          path: /import
          authorizer:
            name: basicAuthorizer
  processProductsFile:
    handler: handler.processProductsFile
    events:
      - s3:
          bucket: ${self:custom.BUCKET_NAME}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
